### ISSUE TITLE
Investigar/Implementar Loggin aplicacion

### ISSUE THREAD

**Issue by tatianamolinari** [proyectoarq1/orgeventos#18]

**Comment by ChristianDaniel** [comment]
- http://blog-archive.copyninja.info/2012/08/logging_issue_with_flask.html
- http://flask.pocoo.org/docs/0.10/errorhandling/

**Comment by ChristianDaniel** [comment]
- https://gist.github.com/ibeex/3257877
- https://realpython.com/blog/python/python-web-applications-with-flask-part-iii/

**Comment by ChristianDaniel** [comment]
<b>Forma de usar</b>
- Importar la app en el archivo en el que quieras hacer logging: 
   from flask import current_app
- y simplemente loguear del tipo que sea necesario:
   current_app.logger.warning('A warning log text')  
   current_app.logger.error('A error log text')

---

<u> Breve aclaración </u>
En el routes.py se agrega el archivo de configuración que define el path dónde se guardan los archivos de log(1 por día, manteniéndose por 7 días), con un formato especial.
Una linea de log de ejemplo:
<i>[2015-10-07 02:05:16,414] {routes.py:25} WARNING - A warning occurred</i>
